{% set version = '1.6-6' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-plm
  version: {{ version|replace("-", "_") }}

source:
  fn: plm_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/plm_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/plm/plm_{{ version }}.tar.gz
  sha256: 05f5494b5b4b018c149b193671a60c32753504034a4142be51a27ebc3e5224a8


  # patches:
   # List any patch files here
   # - fix.patch

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: AER, car, pcse, clusterSEs, clubSandwich, pglm, spdep, splm, statmod, Ecdat, pder, stargazer, texreg, foreign
requirements:
  build:

  host:
    - r-base
    - r-formula >=0.2_0
    - r-mass
    - r-bdsmatrix
    - r-lattice
    - r-lmtest
    - r-maxlik
    - r-nlme
    - r-sandwich
    - r-zoo

  run:
    - r-base
    - r-formula >=0.2_0
    - r-mass
    - r-bdsmatrix
    - r-lattice
    - r-lmtest
    - r-maxlik
    - r-nlme
    - r-sandwich
    - r-zoo

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('plm')"           # [not win]
    - "\"%R%\" -e \"library('plm')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://cran.r-project.org/package=plm, https://r-forge.r-project.org/projects/plm/
  license: GPL (>= 2)
  summary: A set of estimators and tests for panel data econometrics.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: plm
# Version: 1.6-6
# Date: 2017-10-31
# Title: Linear Models for Panel Data
# Authors@R: c(person(given = "Yves",      family = "Croissant",    role = c("aut", "cre"), email = "yves.croissant@univ-reunion.fr"), person(given = "Giovanni",  family = "Millo",        role = "aut", email = "Giovanni.Millo@Generali.com"), person(given = "Kevin",     family = "Tappe",        role = "aut", email = "kevin.tappe@bwi.uni-stuttgart.de"), person(given = "Ott",       family = "Toomet",       role = "ctb", email = "otoomet@gmail.com"), person(given = "Christian", family = "Kleiber",      role = "ctb", email = "Christian.Kleiber@unibas.ch"),  person(given = "Achim",     family = "Zeileis",      role = "ctb", email = "Achim.Zeileis@R-project.org"), person(given = "Arne",      family = "Henningsen",   role = "ctb", email = "arne.henningsen@googlemail.com"), person(given = "Liviu",     family = "Andronic",     role = "ctb", email = "landronimirc@gmail.com"), person(given = "Nina",      family = "Schoenfelder", role = "ctb", email = "nina.schoenfelder@fernuni-hagen.de"))
# Depends: R (>= 3.1.0), Formula (>= 0.2-0), stats
# Imports: MASS, bdsmatrix, zoo, nlme, sandwich, lattice, lmtest, maxLik
# Suggests: AER, car, pcse, clusterSEs, clubSandwich, pglm, spdep, splm, statmod, Ecdat, pder, stargazer, texreg, foreign
# Description: A set of estimators and tests for panel data econometrics.
# License: GPL (>= 2)
# URL: https://cran.r-project.org/package=plm, https://r-forge.r-project.org/projects/plm/
# Author: Yves Croissant [aut, cre], Giovanni Millo [aut], Kevin Tappe [aut], Ott Toomet [ctb], Christian Kleiber [ctb], Achim Zeileis [ctb], Arne Henningsen [ctb], Liviu Andronic [ctb], Nina Schoenfelder [ctb]
# Maintainer: Yves Croissant <yves.croissant@univ-reunion.fr>
# Repository: CRAN
# Repository/R-Forge/Project: plm
# Repository/R-Forge/Revision: 644
# Repository/R-Forge/DateTimeStamp: 2017-11-07 03:41:50
# Date/Publication: 2017-11-07 17:22:35 UTC
# NeedsCompilation: no
# Packaged: 2017-11-07 04:25:28 UTC; rforge

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
