travis:
  secure:
    BINSTAR_TOKEN: nm4vHQEkXMyu6kIS0S7ZXmyfPO31InGzO8ioXmVtOzbmQr3w5CfS8GxarRKkFIrqC5edHRa5zsySfC3jy432o4e4vbNff2pTKH8Jiawfx3FjT6odoAaqH0lvY0oKUtafG+8AqYgJeFoCPW1JT81b1h+y11Il1tTST248LiP2gvnDAaulZDbBEIl6Auhl/VXGXUVcnnz7pdcl8T35bqlNUg36SQ5q0Mo+sCMh78vXZvDjxySUiqatzPpVksz+pV4OUT7FwhI2NMdQalJZgngUkxuRHr50KqMDd0ux9N9oKd/QGgP+DyVTRcey6MOvsKma4uAjiK1W8IJIz4bzudXhanYGcfLoM+SlHuMi00zOn8TYeLSh6mJhdBoYNR6Ev6mivhsg6H4znx8kFBJDJ1K5x7siOzbETARBc4e+Xsraykcj/yBTEvWSYhY5eN9+J3Pp6w+SienwezJhf8eBLnML4zDErSn7lsebOsMlIHfqBLpVOH4BvWmPR4frnuDhQXQeUofXrndEJbOao4MCJuCPCUVYPxWbPS7LxhdGnRB22tRlSyQP/gIB8EWREV1S+lKzo5TgGGzSwNOSH1KTSbcwChAHrHdN94Yw7L8KkRHNXyFe5gIE4UMWbdz+l/dozSx6eujGLmvAzFkaqPgb3A/aDxS46v31N8ILem+EP5N/qdE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
