travis:
  secure:
    BINSTAR_TOKEN: IsMGUrZ+nx7b1j+SMlzFnTH+slx1hp0z7NUJDtUXtfV1kx7q39+bDemDu1SfF6bHrSkQ9jI7vxa1VpUPQiOVrwzPcN0K7KxPoEml3ekFXkoM4bUNjYSZm5gpdfnYGoOcIFGjgtgfC5QyMe9QW/okSWp8IwLHkS3TdC+kT9TqueNfYz8Wgjxx4y0HCb5FNkYchPDHVc1tY/tAw2oYuWffAq80qbWaKgmvBHKF25TqlYVNNugKmk31l6YHNuCMiaUBd9DlG0oI31S+IkOZRs9SKKbLFWZOUtpzl9302hMTNV5m29cw2EVCWYbnWtzUqhLT7p/uY3Hn2lmTy3ElymnNFb6G9PyF7oPbdWlPznsWmeAYByXb3FHWvnQhAzvEkW6Ult7TOem0crOBZTk5aArC9nXSqyWt+vCSrlSr7PfWNwDUAQVbEdy1lDtmuVgrQEa6Xg8s8r1NFk2g5bhOvAGoWdqVsmTHt3NHp+LctGBXNI7yOV2sm4VAm3ENkzNz/ExpBhcHjDXdpeePGKbScshKnoOTmqb9VI6RSDoEaQ/cl9GrUdgwKfVNeOJ9kgXL+4ICpxm9/dALnjJM0bCGG0XTt0QMPnzRYkZlEIr5cw9WykQLvrVvTzkA0puNvzSVsbKgfe59PGbhjBY7IAcJT4W1h2y5YTKUwLFpSDOFDpeVY5I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
